jb.component('phones', { passiveData: [{
    "hits": 34398,
    "title": "alcatel 3C",
    "image": "https://cdn2.gsmarena.com/vv/bigpic/alcatel-3c-.jpg",
    "Technology": "GSM / HSPA / LTE",
    "2G bands": "GSM 850 / 900 / 1800 / 1900 - SIM 1 &amp; SIM 2 (dual-SIM)",
    "3G bands": "HSDPA 850 / 900 / 1900 / 2100 ",
    "4G bands": " LTE",
    "Speed": "HSPA 42.2/11.5 Mbps, LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "Announced": "2018, January",
    "Status": "Coming soon. Exp. release 2018, Q2",
    "Dimensions": "161 x 76 x 7.9 mm (6.34 x 2.99 x 0.31 in)",
    "Weight": "169 g (5.96 oz)",
    "SIM": "Dual SIM (dual stand-by)",
    "Type": "IPS LCD capacitive touchscreen, 16M colors",
    "Size": "6.0 inches, 92.9 cm<sup>2</sup> (~75.9% screen-to-body ratio)",
    "Resolution": "720 x 1440 pixels, 18:9 ratio (~268 ppi density)",
    "Multitouch": "Yes",
    "OS": "Android 7.1 (Nougat)",
    "Chipset": "Mediatek MT8321",
    "CPU": "Quad-core 1.3 GHz Cortex-A7",
    "GPU": "Mali-400",
    "Card slot": "microSD, up to 128 GB",
    "Internal": "16 GB, 1 GB RAM",
    "Primary": "8 MP, autofocus, LED flash",
    "Features": "Geo-tagging, touch focus, face detection, HDR, panorama",
    "Video": "1080p@30fps",
    "Secondary": "5 MP",
    "Alert types": "Vibration; MP3, WAV ringtones",
    "Loudspeaker": "Yes",
    "3.5mm jack": "Yes",
    "WLAN": "Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot",
    "Bluetooth": "4.2, A2DP, LE",
    "GPS": "Yes, with A-GPS",
    "Radio": "To be confirmed",
    "USB": "microUSB 2.0",
    "Sensors": "Fingerprint (rear-mounted), accelerometer, proximity",
    "Messaging": "SMS(threaded view), MMS, Email, Push Mail, IM",
    "Browser": "HTML5",
    "Colors": "Black, Gold, Blue",
    "Price": "About 130 EUR"
  }, {
    "hits": 130873,
    "title": "alcatel Idol 5s",
    "image": "https://cdn2.gsmarena.com/vv/bigpic/alcatel-idol-5s.jpg",
    "Technology": "GSM / HSPA / LTE",
    "2G bands": "GSM 850 / 900 / 1800 / 1900 ",
    "3G bands": "HSDPA 850 / 900 / 1900 / 2100 ",
    "4G bands": "LTE band 1(2100), 3(1800), 7(2600), 8(900), 20(800), 28(700)",
    "Speed": "HSPA 42.2/11.5 Mbps, LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "Announced": "2017, September",
    "Status": "Available. Released 2017, September",
    "Dimensions": "148.6 x 72 x 7.5 mm (5.85 x 2.83 x 0.30 in)",
    "Weight": "147 g (5.19 oz)",
    "SIM": "Nano-SIM",
    "Type": "IPS LCD capacitive touchscreen, 16M colors",
    "Size": "5.2 inches, 74.5 cm<sup>2</sup> (~69.7% screen-to-body ratio)",
    "Resolution": "1080 x 1920 pixels, 16:9 ratio (~424 ppi density)",
    "Multitouch": "Yes",
    "Protection": "Oleophobic coating",
    "OS": "Android 7.1 (Nougat)",
    "Chipset": "Mediatek MT6757 Helio P20",
    "CPU": "Octa-core (4x2.35 GHz Cortex-A53 &amp; 4x1.65 GHz Cortex-A53)",
    "GPU": "Mali-T880 MP2",
    "Card slot": "microSD, up to 256 GB",
    "Internal": "32 GB, 3 GB RAM",
    "Primary": "12 MP (f/2.0, 1/2.8\", 1.25 ï¿½m), phase detection autofocus, dual-LED dual-tone flash",
    "Features": "Geo-tagging, touch focus, face detection, HDR, panorama",
    "Video": "1080p@30fps",
    "Secondary": "8 MP (f/2.0, 1/3.2\", 1.4 ï¿½m)",
    "Alert types": "Vibration; MP3, WAV ringtones",
    "Loudspeaker": "Yes, with stereo speakers",
    "3.5mm jack": "Yes",
    "WLAN": "Wi-Fi 802.11 a/b/g/n/ac, dual-band, WiFi Direct, hotspot",
    "Bluetooth": "4.2, A2DP, LE",
    "GPS": "Yes, with A-GPS",
    "Radio": "FM radio with RDS",
    "USB": "2.0, Type-C 1.0 reversible connector, USB On-The-Go",
    "Sensors": "Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass",
    "Messaging": "SMS(threaded view), MMS, Email, Push Email, IM",
    "Browser": "HTML5",
    "Stand-by": "Up to 500 h (2G) / Up to 500 h (3G)",
    "Talk time": "Up to 18 h (2G) / Up to 18 h (3G)",
    "Colors": "Dark Gray",
    "Price": "About 400 EUR"
  }, {
    "hits": 126129,
    "title": "alcatel Idol 5",
    "image": "https://cdn2.gsmarena.com/vv/bigpic/alcatel-idol-5.jpg",
    "Technology": "GSM / HSPA / LTE",
    "2G bands": "GSM 850 / 900 / 1800 / 1900 ",
    "3G bands": "HSDPA 850 / 900 / 1900 / 2100 ",
    "4G bands": "LTE band 1(2100), 3(1800), 7(2600), 8(900), 20(800), 28(700)",
    "Speed": "HSPA 42.2/5.76 Mbps, LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "Announced": "2017, September",
    "Status": "Available. Released 2017, September",
    "Dimensions": "148 x 73 x 7.5 mm (5.83 x 2.87 x 0.30 in)",
    "Weight": "155 g (5.47 oz)",
    "SIM": "Nano-SIM",
    "Type": "LTPS IPS LCD capacitive touchscreen, 16M colors",
    "Size": "5.2 inches, 74.9 cm<sup>2</sup> (~69.3% screen-to-body ratio)",
    "Resolution": "1080 x 1920 pixels, 16:9 ratio (~423 ppi density)",
    "Multitouch": "Yes",
    "Protection": "Asahi Dragontrail Glass, oleophobic coating",
    "OS": "Android 7.1 (Nougat)",
    "Chipset": "Mediatek MT6753",
    "CPU": "Quad-core 1.3 GHz Cortex-A53",
    "GPU": "Mali-T720MP3",
    "Card slot": "microSD, up to 256 GB",
    "Internal": "16 GB, 3 GB RAM",
    "Primary": "13 MP (f/2.0, 1/3\", 1.12 ï¿½m), phase detection autofocus, dual-LED dual-tone flash",
    "Features": "Geo-tagging, touch focus, face detection, HDR",
    "Video": "1080p@30fps",
    "Secondary": "5 MP (f/2.4, 1/5\", 1.12 ï¿½m), 720p",
    "Alert types": "Vibration; MP3, WAV ringtones",
    "Loudspeaker": "Yes",
    "3.5mm jack": "Yes",
    "WLAN": "Wi-Fi 802.11, b/g/n, WiFi Direct, hotspot",
    "Bluetooth": "4.2, A2DP, LE",
    "GPS": "Yes, with A-GPS, GLONASS",
    "Radio": "FM radio",
    "USB": "microUSB 2.0, USB On-The-Go",
    "Sensors": "Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass",
    "Messaging": "SMS(threaded view), MMS, Email, Push Email, IM",
    "Browser": "HTML5",
    "Colors": "Metal Silver, Metal Black",
    "Price": "About 240 EUR"
  }, {
    "hits": 73624,
    "title": "alcatel A7 XL",
    "image": "https://cdn2.gsmarena.com/vv/bigpic/alcatel-a7-xl.jpg",
    "Technology": "GSM / HSPA / LTE",
    "2G bands": "GSM 850 / 900 / 1800 / 1900 - SIM 1 &amp; SIM 2 (dual-SIM model only)",
    "3G bands": "HSDPA 850 / 900 / 1900 / 2100 ",
    "4G bands": "LTE band 1(2100), 3(1800), 7(2600), 8(900), 20(800), 28(700)",
    "Speed": "HSPA 42.2/11.5 Mbps, LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "Announced": "2017, September",
    "Status": "Available. Released 2017, November",
    "Dimensions": "159.6 x 81.5 x 8.7 mm (6.28 x 3.21 x 0.34 in)",
    "Weight": "175 g (6.17 oz)",
    "SIM": "Single SIM or Dual SIM",
    "Type": "LTPS IPS LCD capacitive touchscreen, 16M colors",
    "Size": "6.0 inches, 99.2 cm<sup>2</sup> (~76.3% screen-to-body ratio)",
    "Resolution": "1080 x 1920 pixels, 16:9 ratio (~367 ppi density)",
    "Multitouch": "Yes, up to 10 fingers",
    "Protection": "Asahi Dragontrail Glass",
    "OS": "Android 7.1 (Nougat)",
    "Chipset": "Mediatek MT6750S",
    "CPU": "Octa-core (4x1.5 GHz &amp; 4x1.0 GHz)",
    "Card slot": "microSD, up to 32 GB",
    "Internal": "32 GB, 3 GB RAM",
    "Primary": "Dual: 12 MP + 2 MP, phase detection autofocus, dual-LED dual-tone flash",
    "Features": "Geo-tagging, touch focus, face detection, HDR, panorama",
    "Video": "1080p@30fps",
    "Secondary": "5 MP, LED flash, 1080p",
    "Alert types": "Vibration; MP3, WAV ringtones",
    "Loudspeaker": "Yes",
    "3.5mm jack": "Yes",
    "WLAN": "Wi-Fi 802.11 a/b/g/n, Wi-Fi Direct, hotspot",
    "Bluetooth": "4.2, A2DP, LE",
    "GPS": "Yes, with A-GPS",
    "Radio": "To be confirmed",
    "USB": "microUSB 2.0",
    "Sensors": "Fingerprint (rear-mounted), accelerometer, proximity, compass",
    "Messaging": "SMS(threaded view), MMS, Email, Push Mail, IM",
    "Browser": "HTML5",
    "Stand-by": "Up to 800 h (2G) / Up to 750 h (3G)",
    "Talk time": "Up to 18 h (2G) / Up to 17 h (3G)",
    "Colors": "Metal Black, Metal Blue, Metal Gold, Rose Gold",
    "Price": "About 280 EUR"
  }] 
})